SourceFile/BossMonster.cpp, SourceFile/Goblin.cpp, SourceFile/Monster.cpp, SourceFile/Orc.cpp, SourceFile/Troll.cpp, headerFile/BossMonster.h, headerFile/Goblin.h, headerFile/Monster.h, headerFile/Orc.h, headerFile/Troll.h
=> Monster Constructor update

Project_TextRPG.vcxproj, Project_TextRPG.vcxproj.filters, SourceFile/MyMath.cpp
=> update : static_cast

SourceFile/Character.cpp, headerFile/Character.h
- getgold함수 추가
- setgold함수 추가: +값은 획득 값, -값은 소모 값으로 적용되도록 작성
- IsValidName함수가 검증 후 검증된 이름을 string으로 반환하도록 수정
=> feat: get/setgold 함수 추가 및 이름 검증 반환값 수정

headerFile/BossMonster.h
=> +boss ability update

headerFile/BossMonster.h, headerFile/GameManager.h, headerFile/Orc.h, headerFile/Shop.h, headerFile/Troll.h
=> monsterupdate

headerFile/Character.h
=> style: for test

SourceFile/Character.cpp, SourceFile/DecoWord.cpp, SourceFile/Monster.cpp, SourceFile/MyMath.cpp, headerFile/Character.h, headerFile/GameManager.h, headerFile/Monster.h, headerFile/MonsterData.h, headerFile/MyMath.h, headerFile/Shop.h
=> consol update

SourceFile/Character.cpp, headerFile/Character.h
=> feat: set name

SourceFile/Character.cpp, headerFile/Character.h
- SetName함수의 인자 타입을 const인자 타입으로 변경하였습니다.
=> modify: changed function parameter

SourceFile/Character.cpp
- 공백값 인식을 위해 이름 입력을 단순 cin이 아닌 getline으로 받도록 수정
=> modify: edit name input method

SourceFile/Shop.cpp, headerFile/Shop.h
=> JCH_Shop_3

SourceFile/Character.cpp, SourceFile/Project_TextRPG.cpp
=> modify: input character name

SourceFile/GameManager.cpp, SourceFile/MonsterData.cpp, SourceFile/MyMath.cpp, SourceFile/Project_TextRPG.cpp, headerFile/MyMath.h
=> pressanykey update

SourceFile/GameManager.cpp, SourceFile/MyMath.cpp, SourceFile/Shop.cpp, headerFile/Monster.h, headerFile/MyMath.h, headerFile/Shop.h
상점 접근불가 숫자 반환처리, 숫자만 가려받는 함수GetValidNumber(), 전투 진입 시 상점 초기화
=> JCH_Shop_4

SourceFile/Character.cpp, SourceFile/GameManager.cpp, SourceFile/Project_TextRPG.cpp, headerFile/GameManager.h
=> phase update

SourceFile/Character.cpp, SourceFile/GameManager.cpp, SourceFile/Monster.cpp, headerFile/GameManager.h, headerFile/Monster.h, headerFile/MonsterData.cpp, headerFile/MonsterData.h
=> Lgw_Add_GetGold

SourceFile/GameManager.cpp
=> fix_InitializeShop()

SourceFile/Character.cpp, SourceFile/Shop.cpp
-아이템삭제 함수 추가
-가독성 증가(띄어쓰기)
-무게 증가 감소
=> Shop_update

SourceFile/Character.cpp, headerFile/Character.h
=> feat: SetMaxHealth

SourceFile/Character.cpp
- 상태보기 실행시마다 아이템 공격력이 배수가 되는 오류 해결
=> modify: GetItemAttack

SourceFile/Character.cpp
- 최대 인벤토리 무게 증량
- 상태보기에서 인벤토리 공간 출력
=> modify: maxInventoryWeight

SourceFile/Character.cpp
- 상태보기 출력값 수정
- 인벤토리 무게 조정 방식 변경
- 플레이어  체력 최하 0으로 설정
=> modify: some function

SourceFile/Character.cpp
-체력장비 해제 시 현재 체력이 최대체력을 넘으면 현재체력 조정
=> feat: adjust health when adjust maxHealth

SourceFile/Dragon.cpp, SourceFile/Goblin.cpp, SourceFile/Orc.cpp, SourceFile/Project_TextRPG.cpp, SourceFile/Troll.cpp, headerFile/Dragon.h, headerFile/Goblin.h, headerFile/Monster.h, headerFile/Troll.h
=> monster getitem update

Project_TextRPG.vcxproj, SourceFile/Character.cpp, headerFile/TextColor.h
- 텍스트의 컬러를 간단히 입힐 수 있는 기능을 추가했습니다.
- 전투 후 골드 획득 시 메시지 출력
=> feat: text color & get gold message

SourceFile/Character.cpp
=> modify:  input name interface

SourceFile/Character.cpp, headerFile/Character.h
=> modify: seperate text output func

SourceFile/Character.cpp, SourceFile/GameManager.cpp, headerFile/GameManager.h
=> feat: add ending

SourceFile/GameManager.cpp, headerFile/Goblin.h, headerFile/GraphicInterface.h, headerFile/Monster.h, headerFile/Orc.h, headerFile/Pitta.h, headerFile/Troll.h
=> monster update

SourceFile/Character.cpp, SourceFile/Project_TextRPG.cpp
- 캐릭터 이름 입력 시 char 변환 과정 오류 위험 해결
=> fix: character name input logic

Project_TextRPG.vcxproj, SourceFile/GameManager.cpp, SourceFile/TextColor.cpp, headerFile/GraphicInterface.h, headerFile/Monster.h, headerFile/TextColor.h
=> monster textcolor update

SourceFile/Character.cpp
=> feat: add test output

SourceFile/Character.cpp, SourceFile/GameManager.cpp
=> modify: edit some text

SourceFile/GameManager.cpp
=> modify: add end credits

SourceFile/GameManager.cpp, SourceFile/Project_TextRPG.cpp
=> color & error update

SourceFile/GameManager.cpp
=> modify: boss battle sounds

SourceFile/Character.cpp, SourceFile/GameManager.cpp, SourceFile/Project_TextRPG.cpp
- 시작시 포션하나를 추가
- 포션과 골드 증정 안내 문구를 추가
=> feat: add start potion & recovery

SourceFile/GameManager.cpp
=> modify: edit ending credits

SourceFile/GameManager.cpp
=> add init_inv_Logic

SourceFile/GameManager.cpp, SourceFile/Sounds.cpp, headerFile/Sounds.h
=> feat: opening bgm
